# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Bobby Is All Right!"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Sally Is All Right!"
# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  bobby_sally:
    jobs:
     - bobby
     - sally